Update pr-ci.yml (#97)
* Update pr-ci.yml

Version 3.7 was not found in the local cache
Error: Version 3.7 with arch x64 not found

To resolve above error I am replacing the version to 3.8 which is a stable version and is available in local cache

* Update pr-ci.yml